/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author rosal
 */
public class Opciones extends javax.swing.JFrame
{

    /**
     * Creates new form Opciones
     */
    public Opciones()
    {
        this.setLocation(100, 30);
        initComponents();
    }

    @Override
    public Image getIconImage()
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("iconos/mochila.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenuItem11.setText("jMenuItem11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BackApp v0");
        setFont(new java.awt.Font("DengXian", 1, 18)); // NOI18N
        setIconImage(getIconImage());
        setResizable(false);

        jLabel1.setText("Fecha y hora:");

        jLabel2.setText("Clase actual: Administracion");

        jButton1.setText("abri libreta");

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/074-question.png"))); // NOI18N
        jMenu1.setFont(new java.awt.Font("DengXian", 0, 18)); // NOI18N
        jMenuBar2.add(jMenu1);

        jMenu5.setText("Configuraciones");
        jMenu5.setFont(new java.awt.Font("DengXian", 0, 18)); // NOI18N

        jMenu7.setText("Notificaciones");
        jMenu7.setFont(new java.awt.Font("DengXian", 0, 18)); // NOI18N

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Notificar siguiente clase");
        jMenu7.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setText("Silenciar notificaciones");
        jMenu7.add(jCheckBoxMenuItem2);

        jMenu5.add(jMenu7);

        jMenuItem2.setFont(new java.awt.Font("DengXian", 0, 18)); // NOI18N
        jMenuItem2.setText("Horario");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuItem15.setFont(new java.awt.Font("DengXian", 0, 18)); // NOI18N
        jMenuItem15.setText("Compañeros");
        jMenu5.add(jMenuItem15);

        jMenuBar2.add(jMenu5);

        jMenu2.setText("Libretas");
        jMenu2.setFont(new java.awt.Font("DengXian", 0, 18)); // NOI18N

        jMenu4.setText("Bases de datos");
        jMenu4.setFont(new java.awt.Font("DengXian", 0, 18)); // NOI18N

        jMenuItem5.setFont(new java.awt.Font("DengXian", 0, 18)); // NOI18N
        jMenuItem5.setText("Abrir");
        jMenu4.add(jMenuItem5);
        jMenu4.add(jSeparator4);

        jMenuItem10.setFont(new java.awt.Font("DengXian", 0, 18)); // NOI18N
        jMenuItem10.setText("Hoja 1");
        jMenu4.add(jMenuItem10);

        jMenuItem12.setFont(new java.awt.Font("DengXian", 0, 18)); // NOI18N
        jMenuItem12.setText("Hoja 2");
        jMenu4.add(jMenuItem12);

        jMenuItem13.setFont(new java.awt.Font("DengXian", 0, 18)); // NOI18N
        jMenuItem13.setText("Hoja 3");
        jMenu4.add(jMenuItem13);

        jMenu2.add(jMenu4);

        jMenu6.setText("Administracion");
        jMenu6.setFont(new java.awt.Font("DengXian", 0, 18)); // NOI18N

        jMenuItem14.setFont(new java.awt.Font("DengXian", 0, 18)); // NOI18N
        jMenuItem14.setText("Abrir");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem14);
        jMenu6.add(jSeparator5);

        jMenuItem6.setFont(new java.awt.Font("DengXian", 0, 18)); // NOI18N
        jMenuItem6.setText("Hoja 1");
        jMenu6.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("DengXian", 0, 18)); // NOI18N
        jMenuItem7.setText("Hoja 2");
        jMenu6.add(jMenuItem7);

        jMenu2.add(jMenu6);
        jMenu2.add(jSeparator1);

        jMenuItem8.setFont(new java.awt.Font("DengXian", 0, 18)); // NOI18N
        jMenuItem8.setText("Crear nueva libreta");
        jMenu2.add(jMenuItem8);

        jMenuItem9.setFont(new java.awt.Font("DengXian", 0, 18)); // NOI18N
        jMenuItem9.setText("Eliminar libreta");
        jMenu2.add(jMenuItem9);
        jMenu2.add(jSeparator3);

        jMenuItem3.setFont(new java.awt.Font("DengXian", 0, 18)); // NOI18N
        jMenuItem3.setText("Importar");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("DengXian", 0, 18)); // NOI18N
        jMenuItem4.setText("Exportar");
        jMenu2.add(jMenuItem4);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem14ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem14ActionPerformed
        new Libreta().setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem2ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem2ActionPerformed
        new Horario().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Opciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
