/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package backapp.configuracion;

import java.awt.Color;

/**
 *
 * @author rosal
 */
public class CuadroHorario extends javax.swing.JPanel
{

    /**
     * Creates new form CuadroHorario
     */
    public CuadroHorario(Color color, String materia, String horainicio, String horafin, String profe)
    {
        initComponents();
        this.materia.setText(materia);
        this.horainicio.setText(horainicio);
        this.horafin.setText(horafin);
        this.profe.setText(profe);
        this.setBackground(color);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        materia = new javax.swing.JLabel();
        horainicio = new javax.swing.JLabel();
        profe = new javax.swing.JLabel();
        horafin = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(100, 110));
        setPreferredSize(new java.awt.Dimension(100, 110));

        materia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        materia.setText("Materia");

        horainicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        horainicio.setText("inicia");

        profe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profe.setText("Profe");

        horafin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        horafin.setText("termina");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(horainicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(materia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(horafin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(materia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(horainicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(horafin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(profe)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel horafin;
    private javax.swing.JLabel horainicio;
    private javax.swing.JLabel materia;
    private javax.swing.JLabel profe;
    // End of variables declaration//GEN-END:variables
}
