package backapp;

import clases.HojaLibreta;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.commons.io.FilenameUtils;

/**
 *
 * @author rosal
 */
public class Hoja extends javax.swing.JPanel
{

    public HojaLibreta texto;
    private File[] imagenes;
    public String path;
    private File libreta;

    protected ArrayList<String> label = new ArrayList<>();
    protected ArrayList<File> ImagenesNuevas = new ArrayList<>();

    /**
     * Creates new form Hoja
     */
    public Hoja(File hoja)
    {
        initComponents();
        this.libreta = hoja;
        path = hoja.getAbsolutePath() + "\\Text.dat";
        try
        {
            ObjectInputStream file = new ObjectInputStream(new FileInputStream(path));
            texto = (HojaLibreta) file.readObject();
            file.close();
        } catch (ClassNotFoundException ex)
        {
            System.out.println("La clase no existe o diferente");
        } catch (IOException e)
        {
        }
        txtTitulo.setText(texto.getTitulo());
        txtArcTexto.setText(texto.getTexto());

        imagenes = hoja.listFiles();
        SepararFormatos();
        Actualizar();
    }

    protected void RenombrarImagenes()
    {
        String s = "";
        for (int i = 0; i < imagenes.length; i++)
        {

            if (!imagenes[i].isDirectory())
            {
                File tmp;
                s = imagenes[i].getParent() + "\\";
                String tam = String.valueOf(imagenes.length);
                String ii = String.valueOf(i);
                String ceros = "";
                int t = tam.length() - ii.length();
                if (t == 0 && ii.length() == 1)
                {
                    t = 1;
                }
                for (int j = 0; j < t; j++)
                {
                    ceros += "0";
                }
                s += ceros + i;
                String extencion = FilenameUtils.getExtension(imagenes[i].getName());
                s += "." + extencion;
                tmp = new File(s);
                imagenes[i].renameTo(tmp);
            }
        }
        imagenes = libreta.listFiles();
        SepararFormatos();
    }

    private void SepararFormatos()
    {
        ArrayList<File> tmp = new ArrayList<>();
        for (int i = 0; i < imagenes.length; i++)
        {
            String extencion = FilenameUtils.getExtension(imagenes[i].getName());
            if ((extencion.compareTo("jpg") == 0) || (extencion.compareTo("jpeg") == 0) || (extencion.compareTo("png") == 0))
            {
                tmp.add(imagenes[i]);
            }
        }

        imagenes = new File[tmp.size()];
        for (int i = 0; i < tmp.size(); i++)
        {
            imagenes[i] = tmp.get(i);
        }
    }

    public void Actualizar()
    {
        jPanelImagenes.removeAll();
        label.clear();
        if (imagenes != null)
        {
            for (int i = 0; i < imagenes.length; i++)
            {
                if (!imagenes[i].isDirectory())
                {
                    String tex = RecortarNombre(imagenes[i].getName());
                    ImageIcon icono = new ImageIcon(imagenes[i].getAbsolutePath());
                    JLabel imagen = new JLabel();
                    imagen.setIcon(new ImageIcon(icono.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH)));
                    imagen.setText(tex);
                    imagen.setHorizontalTextPosition(JLabel.CENTER);
                    imagen.setVerticalTextPosition(JLabel.BOTTOM);
                    jPanelImagenes.add(imagen);
                }
            }
            jPanelImagenes.updateUI();
        }
    }
    
    private String RecortarNombre(String nombre)
    {
        String s = "";

        if (nombre.length() > 15)
        {
            int n = nombre.length() - FilenameUtils.getExtension(nombre).length() - 1;
            s = nombre.substring(0, 4) + "..." + nombre.substring(n - 2, n) + "." + FilenameUtils.getExtension(nombre);
        } else
        {
            s = nombre;
        }

        return s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArcTexto = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanelImagenes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnNuevaImagen = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setBackground(new java.awt.Color(234, 239, 210));

        jSplitPane1.setBackground(new java.awt.Color(234, 239, 210));
        jSplitPane1.setDividerLocation(225);

        txtArcTexto.setColumns(20);
        txtArcTexto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtArcTexto.setRows(5);
        jScrollPane1.setViewportView(txtArcTexto);

        jSplitPane1.setRightComponent(jScrollPane1);

        jPanelImagenes.setBackground(new java.awt.Color(234, 239, 210));
        jPanelImagenes.setLayout(new java.awt.GridLayout(0, 1, 50, 30));
        jScrollPane2.setViewportView(jPanelImagenes);

        jSplitPane1.setLeftComponent(jScrollPane2);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Titulo:");

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTitulo.setText("Hoja 1");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tipo de letra");

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Segoe UI", "Arial", "Sans", "Ink Free" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tamaño de letra");

        jComboBox2.setEditable(true);
        jComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "14", "16", "18" }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Agregar imagen:");

        btnNuevaImagen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuevaImagen.setText("seleccionar archivo");
        btnNuevaImagen.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNuevaImagenActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNuevaImagen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar)))
                .addContainerGap())
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnNuevaImagen)
                    .addComponent(btnGuardar))
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGuardarActionPerformed
    {//GEN-HEADEREND:event_btnGuardarActionPerformed

        texto.setTitulo(txtTitulo.getText());
        texto.setTexto(txtArcTexto.getText());

        for (int i = 0; i < ImagenesNuevas.size(); i++)
        {
            try
            {
                //Definimos el destino del archivo, que será la carpeta Imágenes
                String dest = libreta.getAbsolutePath() + "\\" + ImagenesNuevas.get(i).getName();
                Path destino = Paths.get(dest);
                //Definimos el origen, que será el archivo seleccionado
                String orig = ImagenesNuevas.get(i).getPath();
                Path origen = Paths.get(orig);
                //Copiamos el nuevo archivo con la clase Files, reemplazamos si ya existe uno igual.
                Files.copy(origen, destino, REPLACE_EXISTING);
                //Mostramos mensaje de confirmación de la copia
                System.out.println("si");
            } catch (IOException ex)
            {
                System.out.println("no");
            }
        }

        imagenes = libreta.listFiles();
        SepararFormatos();
        RenombrarImagenes();

        try
        {
            ObjectOutputStream file = new ObjectOutputStream(new FileOutputStream(path));
            file.writeObject(texto);
            file.close();
        } catch (IOException ex)
        {
            System.out.println("No se encontro archivo");
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevaImagenActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNuevaImagenActionPerformed
    {//GEN-HEADEREND:event_btnNuevaImagenActionPerformed

        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo de imagen", "png", "jpg", "jpeg");
        JFileChooser elegir = new JFileChooser();
        elegir.setDialogTitle("Seleccione una imagen");
        elegir.setFileFilter(filtro);
        elegir.showOpenDialog(this);
        File imagenNueva = elegir.getSelectedFile();

        if (imagenNueva != null)
        {
            ImagenesNuevas.add(imagenNueva);
            ImageIcon icono = new ImageIcon(imagenNueva.getAbsolutePath());
            JLabel imagen = new JLabel();
            imagen.setIcon(new ImageIcon(icono.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH)));
            imagen.setText(imagenNueva.getName());
            imagen.setHorizontalTextPosition(JLabel.CENTER);
            imagen.setVerticalTextPosition(JLabel.BOTTOM);
            jPanelImagenes.add(imagen);
            jPanelImagenes.updateUI();
        } else
        {
            JOptionPane.showMessageDialog(null, "Por favor eliga una imagen");
        }

    }//GEN-LAST:event_btnNuevaImagenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevaImagen;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelImagenes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea txtArcTexto;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
